version: 0.0
os: linux
files:
  # app.jsを/plotNativeBacnend/にコピーする指示
  - source: /
    destination: /home/ec2-user/plotNativeBacnend/
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
    - location: scripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root

